[package]
name = "pg-dispatcher"
version = "0.1.0"
authors = ["Antônio Roberto <forevertonny@gmail.com>", "Tiago Guimarães <tilacog@gmail.com>"]


[dependencies]
clap = "~2.19.0"
postgres = "0.15"
fallible-iterator = "0.1.3"
