version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk add --update ca-certificates cargo rust openssl openssl-dev && update-ca-certificates
      - run: cargo test -- --test-threads=1

  push_docker:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t comum/pg-dispatcher:latest .
      - run: docker push comum/pg-dispatcher:latest

      - run: docker build -f Dockerfile.alpine -t comum/pg-dispatcher:latest-alpine .
      - run: docker push comum/pg-dispatcher:latest-alpine


workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push_docker:
          requires:
            - build
          filters:
            branches:
              only: master
