version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk add --update ca-certificates cargo rust openssl && update-ca-certificates
      - run: cargo install
      - run: cargo test -- --test-threads=1


  push_docker:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      # with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application container
      - run: docker build -t comum/pg-dispatcher:latest .
      # deploy the container
      - run: docker push comum/pg-dispatcher:latest


workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push_docker:
          requires:
            - build
          filters:
            branches:
              only: master
